version: "3.8"
services:
  flask-app:
    container_name: flask-app
    build: .
  nginx:
    image: nginx:alpine
    volumes:
    - type: bind
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
    ports:
    - target: 80
      published: 80
      protocol: tcp